name: Test & Release

on:
  push:
    branches:
      - master
jobs:
  build_test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Copy&Paste detection
        run: npm run cpd

  release:
    runs-on: ubuntu-latest

    needs: build_test

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check version
        run: echo "::set-output name=version::$(echo v$(jq -r .version package.json))"
        id: version
      - name: Previous tag
        run: echo "::set-output name=previous_tag::$(git describe --abbrev=0 --tags)"
        id: previous_tag
      - name: Tag release
        if: steps.version.outputs.version > steps.previous_tag.outputs.previous_tag
        uses: mathieudutour/github-tag-action@v5.5
        id: new_tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.version }}
          tag_prefix: ''
      - name: Generate changelog
        if: steps.new_tag.outcome == 'success'
        id: changelog
        uses: metcalfc/changelog-generator@v1.0.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: steps.new_tag.outcome == 'success'
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.new_tag.outputs.new_tag }}
          name: "${{ github.event.repository.name }}-${{ steps.new_tag.outputs.new_tag }}"
          body: |
            Release ${{ steps.new_tag.outputs.new_tag }} includes the following commits:

            ${{ steps.changelog.outputs.changelog }}
